name: test

on:
  workflow_dispatch:

jobs:
  build:
    name: Building for tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.70.0

      - name: Build first bin
        uses: actions-rs/cargo@v1
        with:
          command: build-first

      - name: Build second bin
        uses: actions-rs/cargo@v1
        with:
          command: build-second

      - name: Build third bin
        uses: actions-rs/cargo@v1
        with:
          command: build-third
